---
General:
  configs:
    NSGlobalDomain:
      # Dark theme
      AppleInterfaceStyle: Dark

Language & Region:
  configs:
    NSGlobalDomain:
      # Use 24-hour time
      AppleICUForce24HourTime: true
      # Set first day of week
      AppleFirstWeekday:
        type: dictionary
        operation: set-key
        key: gregorian
        value: 2

Accessibility:
  configs:
    NSGlobalDomain:
      # Disable "Shake mouse pointer to locate"
      CGDisableCursorLocationMagnification: true

Keyboard:
  configs:
    NSGlobalDomain:
      # Keyboard: Disable smart quotes and dashes
      NSAutomaticQuoteSubstitutionEnabled: false
      # Keyboard: Disable spelling correction
      NSAutomaticSpellingCorrectionEnabled: false
      WebAutomaticSpellingCorrectionEnabled: false
      # Keyboard: Disable word capitalization
      NSAutomaticCapitalizationEnabled: false
      # Keyboard: Disable period substitution
      NSAutomaticPeriodSubstitutionEnabled: false
      # Keyboard: Remove all text replacement rules
      NSUserDictionaryReplacementItems:
        type: array
        operation: clear

Trackpad:
  configs:
    NSGlobalDomain:
      # Trackpad: Disable "natural" scroll direction
      com.apple.swipescrolldirection: false

Date & Time:
  kill:
    - SystemUIServer
  configs:
    com.apple.menuextra.clock:
      # Display only time in system clock
      DateFormat: HH:mm:ss

Finder:
  kill:
    - Finder
  configs:
    NSGlobalDomain:
      # Finder: Show all filename extensions
      AppleShowAllExtensions: true
    com.apple.finder:
      # Show removable media on desktop
      ShowExternalHardDrivesOnDesktop: true
      ShowRemovableMediaOnDesktop: true
      # Hide internal hard disks on desktop
      ShowHardDrivesOnDesktop: false
      # Don't show warning before changing an extension
      FXEnableExtensionChangeWarning: false
      # Don't show warning before removing from iCloud Drive
      FXEnableRemoveFromICloudDriveWarning: false
      # Show Path Bar
      ShowPathbar: true
      # Show Sidebar
      ShowSidebar: true
      # Show Status bar
      ShowStatusBar: true

Dock:
  kill:
    - Dock
  configs:
    com.apple.dock:
      # Auto-hide the Dock
      autohide: true
      # Set size of icons
      tilesize: 50
      # Enable Dock icon magnification
      magnification: true
      # Set Dock icon magnification size
      largesize: 90
      # Don't show recent applications in the Dock
      show-recents: false
      # Don't animate opening applications
      launchanim: false
      # Show indicator lights for open applications in the Dock
      show-process-indicators: true

Battery:
  kill:
    - SystemUIServer
  configs:
    com.apple.menuextra.battery:
      # Show battery percentage in status bar
      ShowPercent: 'YES'

Siri:
  kill:
    - SystemUIServer
  configs:
    com.apple.Siri:
      # Hide Siri from the status bar
      StatusMenuVisible: 0

KeepingYouAwake:
  restart:
    - KeepingYouAwake
  configs:
    info.marcel-dierkes.KeepingYouAwake:
      'info.marcel-dierkes.KeepingYouAwake.ActivateOnLaunch': true
      'info.marcel-dierkes.KeepingYouAwake.BatteryCapacityThreshold': 30
      'info.marcel-dierkes.KeepingYouAwake.BatteryCapacityThresholdEnabled': true
      'info.marcel-dierkes.KeepingYouAwake.LaunchAtLogin': true
      'info.marcel-dierkes.KeepingYouAwake.NotificationsEnabled': true

Itsycal:
  restart:
    - Itsycal
  configs:
    com.mowglii.ItsycalApp:
      HighlightedDOWs: 65
      MoCalendarNumRows: 6
      ShowDayOfWeekInIcon: true
      ShowEventDays: 7
      ShowLocation: true
      ShowMonthInIcon: true
      ShowWeeks: true
      UseOutlineIcon: false
      WeekStartDOW: 1

MonitorControl:
  restart:
    - MonitorControl
  configs:
    me.guillaumeb.MonitorControl:
      enableSliderPercent: 1
      enableSliderSnap: 1
      showTickMarks: 0
      multiKeyboardBrightness: 1
