---
NSGlobalDomain:
  domain: NSGlobalDomain
  restart: false
  configs:
    # Show all filename extensions
    AppleShowAllExtensions: true

Finder:
  domain: com.apple.finder
  configs:
    # Show removable media on desktop
    ShowExternalHardDrivesOnDesktop: true
    ShowRemovableMediaOnDesktop: true
    # Hide internal hard disks on desktop
    ShowHardDrivesOnDesktop: false
    # Don't show warning before changing an extension
    FXEnableExtensionChangeWarning: false
    # Don't show warning before removing from iCloud Drive
    FXEnableRemoveFromICloudDriveWarning: false
    # Show Path Bar
    ShowPathbar: true
    # Show Sidebar
    ShowSidebar: true
    # Show Status bar
    ShowStatusBar: true

Dock:
  domain: com.apple.dock
  configs:
    # Auto-hide the Dock
    autohide: true
    # Set size of icons
    tilesize: 50
    # Enable Dock icon magnification
    magnification: true
    # Set Dock icon magnification size
    largesize: 90
    # Don't show recent applications in the Dock
    show-recents: false
    # Don't animate opening applications
    launchanim: false
    # Show indicator lights for open applications in the Dock
    show-process-indicators: true
